### ISSUE TITLE
Fix RSDL-CSDL conversion to accommodate cases where a singleton is introduced for a keyless type.

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#122]

**Comment by chrisspre** [comment]
@mikepizzo @ralfhandl  the spec still refers to a singleton needing to be a entity type. http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_Singleton . 
What am I missing? How can we generate a CSDL for this?

**Comment by ralfhandl** [comment]
If a type is used in a singleton, it is an entity type, but it doesn't need to have a key.

**Comment by chrisspre** [comment]
The consequence is that a (RSDL) structured type without a key will be translated to a complex type. But even though it might not change structurally, by adding it as a single-valued property in the service (a singleton) it will be suddenly translated to an entity type. 
I do not think it be a technical problem. But it might be a surprise to some users.

**Comment by ralfhandl** [comment]
În OData v5 we will combine entity types and complex types into "structured types", merge navigation properties and properties, and combine $expand and $select into $expect 😄
