### ISSUE TITLE
use capitals for built-in types

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#127]
I note that GraphQL does use capitals for type names; both custom names as well as built-in types, so it looks a little more consistent.

If we think the conventions should be initial caps for custom type names we should do the same for built-in primitive types.

_Originally posted by @mikepizzo in https://github.com/oasis-open/odata-rapid/pull/118#discussion_r498434985_

**Comment by ralfhandl** [comment]
I think using `String` etc. for the built-in types and just omitting the `Edm.` would be also more consistent with OData
