### ISSUE TITLE
specify a namespace for an RSDL file

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#128]
I like it to be able to specify a namespace. 

It has a bit of a larger impact since I believe we a) need to be able to fully qualify (type-) names and b) import/reference other namespaces. 

I would suggest to not specify the namespace as an annotation and not so deep into the document.
I would suggest 
a) one namespace per document and 
b) an (optional ) declaration at the top of the document namespace "hello"  that specifies the namespace name. No needs for any braces since this is for the complete document. I believe that simplifies the syntax and makes it less obtrustive.

Happy to work on the namespace declaration and leave the reference/fqn design for later.

_Originally posted by @chrisspre in https://github.com/oasis-open/odata-rapid/issues/121#issuecomment-702375681_

**Comment by ralfhandl** [comment]
Do we want to add a `namespace` keyword, or just define them implicitly by using qualified names with `type`?

1. implicit namespace 
~~~rsdl
type foo.bar.baz { ... }
~~~

1. explicit namespace similar to Java `package`
~~~rsdl
namespace foo.bar

type baz { ... }
~~~

1. explicit namespace as a nesting construct, similar to C#
~~~rsdl
namespace foo.bar {

  type baz { ... }

}
~~~

In all three cases the qualified name of the type would be `foo.bar.baz`.

**Comment by ralfhandl** [comment]
My favorite is 2.

**Comment by mikepizzo** [comment]
2 definitely works better than 3 if we want to make namespace optional.

What do we want the default namespace to be if no namespace is defined? Elsewhere I suggested "Model", but am open to better suggestions.

**Comment by chrisspre** [comment]
#1 allows multiple namespaces per file which might be more flexibility but create complexity from the get go. #1 is a no for me.

I would like to avoid the nesting level and therefore prefer #2, the "file as package" 
 
> What do we want the default namespace to be if no namespace is defined? Elsewhere I suggested "Model", but am open to better suggestions.

I am ok with model and will try to create a PR with the suggested changes now. (the constant name can be changed easily.

**Comment by GEricson** [comment]
Option #1 seems too open to confusion, mistakes, and misuse.
Option #2 and #3 could both support multiple namespaces per file.   (Namespace block starts with Namespace keyword.)
In either #2 or #3, do multiple uses of the same namespace simply concatenate.
Option #3 could support nested namespaces.  
```
namespace foo {
    namespace bar {
        type baz { ... }
    }
    namespace qux {
        import foo.bar     
        type quux {
            aprop foo.bar.baz
        }
    }
}

```
#2 can also, just with flattened namespace names...
```
namespace foo.bar
        type baz { ... }

namespace foo.qux 
        import foo.bar     
        type quux {
            aprop foo.bar.baz
        }
```

**Comment by chrisspre** [comment]
> Option #2 and #3 could both support multiple namespaces per file. (Namespace block starts with Namespace keyword.)
> In either #2 or #3, do multiple uses of the same namespace simply concatenate.
> Option #3 could support nested namespaces.

My vote goes 100% for one namespace per file. I believe the lost flexibility is more than made up for by the simplicity for the targeted audience.
