### ISSUE TITLE
namespace imports and referencing types in imported models

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#131]
Given that we have namespace declaration now we need to introduce a mechansim to reference the items in there.

**Comment by ralfhandl** [comment]
Let's just
~~~
include com.acme.foo.bar.v22 as foobar
~~~
Or simplify away the aliases 🤔

**Comment by chrisspre** [comment]
> Let's just
> 
> ```
> include com.acme.foo.bar.v22 as foobar
> ```
> 
> Or simplify away the aliases 🤔

This does not specify the file path/ URL of the RSDL file that has definitions of com.acme.foo.bar.v22 .
This is not sufficient for the analysis of the model (and for the transformation into CSDL)

I suggest 
```
import com.acme.foo.bar.v22 as v22 from "v22.rsdl" 
```
with an optional `as v22`

**Comment by ralfhandl** [comment]
In CSDL we use "include" instead of "import". 

How about
~~~rsdl
namespace quux

include com.acme.foo.bar.v22 as foobar from "v22.rsdl" 
include com.acme.foo.baz.v42 as foobaz from "v24.rsdl" 

type ...
~~~

I.e. includes must appear before defining model elements.

**Comment by chrisspre** [comment]
Looks good to me. I prefer import because include sounds a bit like times we used preprocessor. But it is not a big issue.

**Comment by chrisspre** [comment]
Need some clarification about the use of alias

### qualifying type names

After:
```
include com.acme.foo.baz.v42 as foobaz from "v24.rsdl" 
```
can a type `User` from v24.rsdl only be referenced as `foobaz.User`  or can it also be referenced as `com.acme.foo.baz.v42.User` ?

### "alias" syntax

Should the `as {alias}` portion be optional?

And if so is it fair to define
```
include com.acme.foo.baz.v42 from "v24.rsdl"
```
as equivalent to
```
include com.acme.foo.baz.v42 as com.acme.foo.baz.v42 from "v24.rsdl"
```

**Comment by ralfhandl** [comment]
In CSDL aliases are optional. 

In CSDL XML aliases and namespaces can be used interchangeably as type prefixes. 

In CSDL JSON we require consistency: if an alias is defined, it must be used instead of the namespace throughout the document. 

I lean towards the more modern second approach. 

However I found that from an implementation perspective it doesn't make a difference: I always resolve an alias to its namespace, and namespaces without explicit alias use the namespace as alias.

**Comment by chrisspre** [comment]
> In CSDL aliases are optional.
> 
> In CSDL XML aliases and namespaces can be used interchangeably as type prefixes.
> 
> In CSDL JSON we require consistency: if an alias is defined, it must be used instead of the namespace throughout the document.
> 
> I lean towards the more modern second approach.
> 
You seem to list three items. Which one is the second?

**Comment by chrisspre** [comment]
AS discussed today we are changing the syntax to 

# mandatory alias for the one and only namespace in file
include "../common/bar.rsdl" as bar
include "../common/baz" as baz

additional issue needs to be create to address how the path given here can be translated into CSDL reference URIs

**Comment by ralfhandl** [comment]
Do we require the included files to define an explicit namespace? Or can (at most) one of them have no namespace and thus use the implicit `Model` namespace?

**Comment by chrisspre** [comment]
The fact that the name was implicitly "Model" or explicit defined makes little difference. But uniqueness of namespace names and aliases has to be defined.

option 1 if aliases are required and type references can only use the alias:
aliases need to be unique

option 2 if we allow to reference a type by alias or the namespace:
all namespaces and all aliases (combined into a set of names) need to be unique

**Comment by chrisspre** [comment]
> 
> additional issue needs to be create to address how the path given here can be translated into CSDL reference URIs
#146  was created yesterday

**Comment by ralfhandl** [comment]
Option 1 is the way to go: alias from "include" statement must be used to reference "external" types.

Corollary: "internal" types need no qualifier and MUST not specify one.

It is similar to how Node.js modules work.

This is sufficient for the "inner working" of RSDL, but when translating to CSDL each file MUST have a namespace that is unique within the "universe" spanned by everything included directly or indirectly from the "root" file. This namespace could be generated when translating if the RSDL namespaces are not unique.
