### ISSUE TITLE
Add built-in type "Decimal"

### ISSUE THREAD

**Issue by ralfhandl** [oasis-open/odata-rapid#139]
Add built-in type `Decimal` for cases where people would not look kindly at rounding issues potentially caused by using `Double`.

~~~rsdl
fixedPoint: Decimal(5,2) // -999.99 to 999.99 in increments of 0.01
floatingPoint: Decimal   // decimal128 floating-point number
~~~

See https://en.wikipedia.org/wiki/Decimal128_floating-point_format

**Comment by chrisspre** [comment]
fixed as part of #157  see https://github.com/oasis-open/odata-rapid/blob/5147db9835de3bd02a0e3aa9a162a5779d224000/tools/rsdl/rapid-cli/rapid.rdm.transformation/TypeEnvironment.cs#L195
