### ISSUE TITLE
website uses a lot of deprecated packages

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#154]
`npm install` in the website directory produces:

![image](https://user-images.githubusercontent.com/53094940/98969843-1cc82200-24c4-11eb-83a0-95f2e93555c9.png)

**Comment by wtrocki** [comment]
Usually this is easily resolved by configuring renovate. I can help adding it to the repository. 
Also `npm audit` will pinpoint some of the packages so it will reduce number of things.

ALso keep in mind that those are being used only to generate sources so actually website is purely static and is not having any of those dependencies out there <- Actual impact will be minor

**Comment by chrisspre** [comment]
> Usually this is easily resolved by configuring renovate. I can help adding it to the repository.
> Also `npm audit` will pinpoint some of the packages so it will reduce number of things popping out here.

Thank @wtrocki , can you please point me at some documentation for renovate. 

> Also we can keep in mind that those are being used only to generate sources so actually website is purely static and is not having any of those dependencies out there <- Actual impact will be minor

That is good to hear. Thanks for clarifying. Not fully understanding the build process and seeing these warning is just a bit concerning and I didn't have the time to look deeper into it.

I would appreciate if you can have a look at https://github.com/oasis-open/odata-rapid/blob/master/docs/rsdl/rapid-pro-rsdl-semantics.mdx 
The extended markdown syntax is quite elaborate and you might have ideas to improve it and/or get rid of some of the markdownlint warnings. Also would like to register a language prefix for the ` ```rsdl ` sections.

**Comment by chrisspre** [comment]
current state:

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
