### ISSUE TITLE
Add Annotation support to RSDL.

### ISSUE THREAD

**Issue by ralfhandl** [oasis-open/odata-rapid#164]
Use `@Validation.AllowedValues` as the litmus test. 

Syntax could be JSON5-ish CSDL JSON representation.

**Comment by ralfhandl** [comment]
Variant 1: place annotation before model element - lots of stuff to read before the interesting bits

~~~rsdl
@Core.Description: "An order for goods or services"
type Order {
  @Core.Description: "The status of an order"
  @Validation.AllowedValues: [
    { Value: 1, @Core.Description: "Order has been submitted", @Core.SymbolicName: "submitted" },
    { Value: 2, @Core.Description: "Order has been fulfilled", @Core.SymbolicName: "fulfilled" },
    { Value: 3, @Core.Description: "Order has been shipped", @Core.SymbolicName: "shipped" },
    { Value: -1, @Core.Description: "Order has been canceled", @Core.SymbolicName: "canceled" },
  ]
  status: Integer?

  @Core.Description: "The point in time the order was created"
  createdAt: DateTime
}
~~~

**Comment by chrisspre** [comment]
> Syntax could be JSON5-ish CSDL JSON representation.

I like the suggestion to user JSON5-ish syntax. But just for reference, the syntax allows a lot of errors. While testing I wrote this:

```
{
    a: ["a" 'b' , "c'",]  
    "b": {d: 1.1 e: false,} ,
    c: [{}, [] true, false 1, null 'hello"', "w\torl\u0020d" ]
}
```

which is "legal" JSON5+optional comma that translates to 
```json
{"a":["a","b","c\u0027"],"b":{"d":1.1,"e":false},"c":[{},[],true,false,1,null,"hello\u0022","w\torl d"]}

```

**Comment by chrisspre** [comment]
#### position 
> Variant 1: place annotation before model element - lots of stuff to read before the interesting bits

Not a big fan of the annotation before the actual element for exactly that reason but I can not think if an alternative.

#### syntax

> ```
> @Core.Description: "An order for goods or services"

That syntactically mixes a little bit the notion of static keywords with more dynamic data/parameters. 
I would prefer:
```
@annotation('Core.Description', "An order for goods or services")
```
and equivalent.

**Comment by ralfhandl** [comment]
Good idea, how about
```
@annotation(Core.Description:'An Order...', Something.Else:true)
type Order {...}
```

Or even
```
@(Core.Description:'An Order...' Something.Else:true)
type Order {...}
```

**Comment by chrisspre** [comment]
I haven't thought through this completely but think the ambiguity of what JSON considers a number and the multiple representations of this in CSDL requires some more thought:

E.g. an annotation like
```
@annotation(Validation.AllowedValues: {[{value: 1}, {value: 1.1} ] )
```
In CSDL JSON this is a relatively straightforward transformation:
```JSON
 "@Org.OData.Validation.V1.AllowedValues": [
        {
          "value": 1
        },
        {
          "value": 1.1
        }
      ]
```
But in CSDL XML the type of the property values is always explicit 

```XML
        <Annotation Term="Org.OData.Validation.V1.AllowedValues">
          <Collection>
            <Record>
              <PropertyValue Property="value" Int="1" />
            </Record>
            <Record>
              <PropertyValue Property="value" Float="1.1" />
            </Record>         
          </Collection>
        </Annotation>
```
The first one is an Int, the second a Float.

Just speculating: can this be 

```XML
        <Annotation Term="Org.OData.Validation.V1.AllowedValues">
          <Collection>
            <Record>
              <PropertyValue Property="value>1</PropertyValue>
            </Record>
            <Record>
              <PropertyValue Property="value">1.1</PropertyValue>
            </Record>         
          </Collection>
        </Annotation>
```

**Comment by chrisspre** [comment]
discussed today and preferred syntax is:

@Core.Description: "best kind of pet"
type Dog
{
    @Core.Description: "a thing"
    @Validation.AllowedValues: [{value: "a"}, {value: 'b'}]
    @key name: String,

    @Core.Description: "hopefully four" 
    numberOfLegs: Integer,
}
