### ISSUE TITLE
RSDL: Add support for generating OpenAPI from RSDL

### ISSUE THREAD

**Issue by mikepizzo** [oasis-open/odata-rapid#201]

**Comment by ralfhandl** [comment]
Should we use our own package https://www.npmjs.com/package/odata-openapi, or some other OpenAPI generator?

**Comment by mikepizzo** [comment]
I used an opensource ODataReader that plugs into OpenAPI's open .Net library as part of the current RSDL tool because it works off of the in-memory Entity Model.  If we move the RSDL tool to typescript where we don't have the common libraries then it probably makes sense to use our odata-openapi package for generation.
