### ISSUE TITLE
Should RSDL allow to optionally specify the name of the entity container?

### ISSUE THREAD

**Issue by ralfhandl** [oasis-open/odata-rapid#207]
The annotation test case https://github.com/oasis-open/odata-rapid/blob/master/tools/rsdl/rapid-cli/rapid.rdm.transformation.tests/data/annotations2/model.rsdl#L34 shows a service definition with a name:

~~~rsdl
service Service1
{
~~~

Is this an intended new feature, not yet mentioned in the ABNF?

**Comment by chrisspre** [comment]
Yes, intentional. When I was working on service annotations I realized that this was not implemented fully.
Happy to add a test case to ensure it is exactly that permanently. 

I am behind on updating ABNF and documentation.

**Comment by mikepizzo** [comment]
In that case, I'll update the OpenAPI generation to use the entity container name, if specified.

**Comment by chrisspre** [comment]
> In that case, I'll update the OpenAPI generation to use the entity container name, if specified.

The [RdmService ](https://github.com/oasis-open/odata-rapid/blob/d3a6d1d1e3d08aa2cff86c78efaba0baecde45cb/tools/rsdl/rapid-cli/rapid.rdm/models/RdmService.cs#L20) model element always has a name no matter if it is specified in the file or not (or in other words it is mandatory and gets the default when not specified in the file, no null handling :-) )

**Comment by mikepizzo** [comment]
Does that mean that (in EdmModel) EdmEntityContainer.Name is always non-null?

**Comment by chrisspre** [comment]
> Does that mean that (in EdmModel) EdmEntityContainer.Name is always non-null?

Correct.

**Comment by ralfhandl** [comment]
> Happy to add a test case to ensure it is exactly that permanently. 

No need, you did that in the `annotations2` test case, where I stumbled over it.
