### ISSUE TITLE
Define how services describe their capabilities

### ISSUE THREAD

**Issue by mikepizzo** [oasis-open/odata-rapid#237]
RAPID is a profile that describes a subset of functionality from the full OData specification. PR #147 defines that subset.

Still, an individual instance of a service will support a subset of that functionality across different paths.

How does the service describe what patterns it supports when requesting data?

We have a capabilities vocabulary for defining supported functionality at a very fine level, which is appropriate for the CSDL view, but is too complex for RSDL. 

We need a simple way in RSDL to describe the basic functionality for each request.

**Comment by mikepizzo** [comment]
Since we are trying to describe the functionality of the service, it makes sense to make this as part of the service definition.
Since capabilities/functionality may differ based on each path, it makes sense to make this part of the top-level element (i.e., entityset/singleton).

We could represent this as RSDL annotations, but we would want special behavior to convert it to a different capability vocabulary syntax in CSDL.  So it is probably clearer to make it built-in (but optional) first-class syntax.

We need to specify:
-paths supported (i.e., do I support navigating through a parent to a child)
-methods supported (post (create), update (patch), delete)
-query options supported (select (perhaps this is implicit), expand (including nested expand options), filter)

We could index capability by verb (POST/GET/PATCH/DELETE) and, for each verb, specify the supported paths and, for each path, the supported query options.

For example, for our Jetsons service we could fully document supported operations, paths, and query options as something like:

~~~
service
{
    competitors: [Company]
    {
      get:
      {
         competitors: {select,expand(employees{select,filter}),filter}
         competitors/{stockSymbol}: {select,expand(employees{select,filter})}
         competitors/{stockSymbol}/employees: {select, filter}
         competitors/{stockSymbol}/employees/{id}: {select}
      }
      post:
      {
        competitors
        competitors/{stockSymbol}/employees
      }
      patch:
      {
        competitors
        competitors/{stockSymbol}
        competitors/{stockSymbol}/employees
      }
      delete: 
      {
        competitors/{stockSymbol}
        competitors/{stockSymbol}/employees/{id}
      }
   }

   company: Company
   {
      get:
      {
        company: {select,expand(employees{select,filter})}
        company/employees: {select,filter}
      }
      post:
      {
        company/employees
      }
      patch:
      {
        competitors
        competitors/{stockSymbol}
        competitors/{stockSymbol}/employees
      }
      delete: 
      {
        competitors/{stockSymbol}
        competitors/{stockSymbol}/employees/{id}
      }
   }
}
~~~

**Comment by ralfhandl** [comment]
I like it, with some tweaks:

- don't repeat the root entity name
- don't give the key a name unless we need to use that name
- don't make the path patterns depend on the number of key properties

**Comment by mikepizzo** [comment]
thanks for the feedback ralf! 

I thought you were supposed to be on vacation?! :-)

**Comment by chrisspre** [comment]
Looks great. 
Just to small observations.
- there are quite a few curly braces which might make it hard to scan this visually. Not sure if other forms of parenthesis would be useful 
- I would have expected the HTTP methods to be spelled with upper case GET, POST...  But I also see the aesthetics of the RSDL language being all lowercase.

**Comment by mikepizzo** [comment]
Do we need to be able to specify, for filter, what properties can be specified in the filter?

**Comment by mikepizzo** [comment]
service
{
    competitors: [Company]
    {
        competitors: 
           get 
	   {
             expand(employees{filter})
             filter
           }
           post
           patch
        /{stockSymbol}:
            get 
            {
              expand(employees{filter})
            }
            patch
            delete
        /{stockSymbol}/employees:
            get
            {
              filter
            }
            post
            patch
        /{stockSymbol}/employees/{id}:
            get
            patch
            delete
   }

   company: Company
   {
       company: 
           get {expand(employees{filter})}
        /employees: 
           get {filter}
           post
        /employees/{id}
           get {filter}
           patch
           delete
    }
}

**Comment by chrisspre** [comment]
DRAFT ABNF


service              = %s"service" "{" 1*serviceMember "}"

serviceMember        = entitySet / singleton / serviceOperation

entitySet            = identifier ":" "[" qualifiedName "]" [ "{" capabilities "}" ]

singleton            = identifier ":" qualifiedName [ "{" capabilities "}" ]

capabilities         = urlFragement ":" 1*methodCapability

methodCapability     = get "{" expandOrFilter 1*("," expandOrFilter) ] }
                     / put
                     / post
                     / patch
                     / delete



expandOrFilter      = "filter"
                    / "expand" [ "(" expandOrFilter ")" ]

**Comment by mikepizzo** [comment]
Note: Christof
1) I added "skip" and "count" and changed "groupBy" to "orderby".
2) I modified "expand" to include the property name
3) This still does not distinguish, for expanded properties, whether the expanded property is collection-valued (in which case collection options are valid) versus non-collection valued.

**Comment by chrisspre** [comment]
> 2. I modified "expand" to include the property name

don't see that change. 

> 3. This still does not distinguish, for expanded properties, whether the expanded property is collection-valued (in which case collection options are valid) versus non-collection valued.

I think that is syntactically only possible in a context sensitive grammar that would know at that point if a property is collection values (and even if it is a valid property name).
Often this is done in a validation step after the parsing.

**Comment by chrisspre** [comment]
next iteration:

```ABNF
capabilities         = urlFragment ":" 1*methodCapability

urlFragment          = "/" [  urlSegment 1*(  "/" urlSegment  )   ] 

urlSegment           = identifier
                     / "{" identifier "}"
                     / "{" "key" "}"

methodCapability     = "get" [ "{" collectionOptions *("," collectionOptions ) "}"  ]
                     / "put"
                     / "post"
                     / "patch"
                     / "delete"


collectionOptions    = "filter"
                     / "orderby"
                     / "top" 
                     / "skip"
                     / "expand" [ "(" identifier [ "{" collectionOptions *("," collectionOptions ) "}" ] ")" ]     

```

**Comment by mikepizzo** [comment]
Sorry; added the comment before submitting my changes.  I took a shot at differentiating between single-valued and collection-valued similar to how we do it in the OData ABNF. The naming suggests when each construct is used but, of course, the ABNF doesn't have the context to know if a urlSegment specifies a single-valued or collection-valued nav prop.

Also, urlSegment is perhaps a bit loose for specifying the navigation path being extended.  It will generally be the nav prop name, but could also be prefixed with one or more complex type or type cast segments. It cannot have interim navigation property segments. But, that might be too complex to try and describe in the ABNF.

**Comment by mikepizzo** [comment]
This addresses what can go in the expand path -- is it too much?

~~~ABNF
service              = "service" "{" 1*serviceMember "}"

serviceMember        = entitySet / singleton / serviceOperation

entitySet            = identifier ":" "[" qualifiedName "]" [ "{" capabilities "}" ]

singleton            = identifier ":" qualifiedName [ "{" capabilities "}" ]

capabilities         = urlFragment ":" 1*methodCapability

urlFragment          = "/" [  urlSegment 1*(  "/" urlSegment  )   ] 

urlSegment           = identifier
                     / "{" identifier "}"
                     / "{" "key" "}"

methodCapability     = "get" [ "{" collectionOptions 1*("," collectionOptions ) "}"  ]
                     / "put"
                     / "post"
                     / "patch"
                     / "delete"

collectionOptions    = "filter"
                     / "orderby"
                     / "top"
                     / "skip"
                     / "count"
                     / "expand" [ "(" expandSpecification 1*("," expandSpecification) ")"]     

expandSpecification = singleValuedExpandSpecification | collectionValuedExpandSpecification

singleValuedExpandSpecification = expandPath

collectionValuedExpandSpecification = expandPath [ "{" collectionOptions "}" ]

expandPath = *[(complexTypeProperty | castSegment) "/"] navigationProperty

navigationProperty = identifier

complexTypeProperty = identifier

castSegment = identifier
~~~

**Comment by ralfhandl** [comment]
> ```abnf
> urlSegment           = identifier         ; we should decide between "{key}" or "{" identifier "}", but not allow both
>                      / "{" identifier "}"
>                      / "{" "key" "}"  
> ```

Using identifiers in all segments, and indicating via `{` and `}` that the segment uses the value instead of the name is more consistent.

**Comment by chrisspre** [comment]
> > ```abnf
> > urlSegment           = identifier         ; we should decide between "{key}" or "{" identifier "}", but not allow both
> >                      / "{" identifier "}"
> >                      / "{" "key" "}"  
> > ```
> 
> Using identifiers in all segments, and indicating via `{` and `}` that the segment uses the value instead of the name is more consistent.

my vote goes to "{" "key" "}". I believe the concrete name(s) of the key here is not adding more information but would require to change it here if the keys change.

**Comment by chrisspre** [comment]
Fore readability I would really prefer a) CAPITAL http methods, and b) write the "full" URLs, even if that seems repetitive when looking at small examples. (e.g. `/company/competitors` for the "company" singleton and "competitors" navigation property ).

**Comment by mikepizzo** [comment]
Discussion 2021-4-15:
1) (Hubert): Don't make me specify all paths for a full-service OData service, because I can't spell out all paths.
2) (Mike): Perhaps we can use wildcards to explicitly specify compliance with patterns, rather than spell them all out
3) Perhaps we could define other common, re-usable patterns

Be explicit on individual paths or be explicit that it supports recursively.

**Comment by darrelmiller** [comment]
I am curious as to why the above examples take a hybrid approach to defining paths.  EntitySet and Singleton are treated differently than navigation properties to entities and collections of entities.
I was imagining the path description mechanism as applying consistently across the entire URL space.  

Something like:

```
servicePaths
{
        /competitors: 
           get 
	   {
             expand(employees{filter})
             filter
           }
           post
           patch
        /competitors/{stockSymbol}:
            get 
            {
              expand(employees{filter})
            }
            patch
            delete
        /competitors/{stockSymbol}/employees:
            get
            {
              filter
            }
            post
            patch
        /competitors/{stockSymbol}/employees/{id}:
            get
            patch
            delete
       /company: 
           get {expand(employees{filter})}
       /company/employees: 
           get {filter}
           post
       /company/employees/{id}:
           get {filter}
           patch
           delete
}
type entityContainer {
   competitors: [company]
   company: company
}

type company {
  employees: [employee]
}

type employee {
}
```
I see two important characteristics of this approach:

- servicePaths is a completely optional concept that layers on top of the set of defined types.  Without defining servicePaths the conventions are identical to CSDL.
- servicePaths can be used to infer entity types that only exist for the purpose of defining path segments.  There should be no need to define types for singletons when the only reason they exist is to create path segments for organizational purposes.

**Comment by chrisspre** [comment]
In addition to what Darrel said in the first bullet point, I like it just visually how the container type is separate from the paths and capabilities. I also don't mind the repetition of the prefixes (/e.g. /company/... ) It makes it very easy to read, explicit and is actually not difficult two write. 
I am not sure about the inference of entity types for singletons. I would probably prefer a very clear and easy to act on warning if the type is missing. Along the lines of "the segment 'bla' is not defined, it appears you are missing an entity type for the singleton 'bla' "

**Comment by darrelmiller** [comment]
@chrisspre I understand your reasoning for not wanting to infer entity types.  This could be just a tooling feature where someone describes paths and types are auto inferred, but the final document requires explicit declarations.

**Comment by garethj-msft** [comment]
> > ```abnf
> > urlSegment           = identifier         ; we should decide between "{key}" or "{" identifier "}", but not allow both
> >                      / "{" identifier "}"
> >                      / "{" "key" "}"  
> > ```
> 
> Using identifiers in all segments, and indicating via `{` and `}` that the segment uses the value instead of the name is more consistent.

Without individualized names for identifiers, we won't later be able to add constraints to the model for what those identifiers should be where there is more than one in a path.   This seems like it would be a real miss, when we want to specify that orderId is a Guid, plus a few magic values, but lineItemId is just a long.  There's really not a strong correspondence here in APIs between the Key of the type and what the values that can be passed as IDs in the path,  it's just the most common thing, and our teams typically do not use the formal alternate-id syntax where the types are easily distinguishable - it's just too clumsy.

**Comment by ralfhandl** [comment]
> servicePaths can be used to infer entity types that only exist for the purpose of defining path segments.  There should be no need to define types for singletons when the only reason they exist is to create path segments for organizational purposes.

Could someone please explain this statement?

In my naïve view paths identify typed resources, and the resource type specifies the response shape. Which can include links to other resources, in OData terminology "navigation properties", whose names can also be appended as additional path segments if one is not interested in the intermediate resource(s).

**Comment by ralfhandl** [comment]
> Without individualized names for identifiers, we won't later be able to add constraints to the model for what those identifiers should be where there is more than one in a path. This seems like it would be a real miss, when we want to specify that orderId is a Guid, plus a few magic values, but lineItemId is just a long.

Those restrictions are defined on the key properties in the resource type.

> There's really not a strong correspondence here in APIs between the Key of the type and what the values that can be passed as IDs in the path

In OData there is a strong correspondence: key segment values MUST match the type of the corresponding key property.

**Comment by darrelmiller** [comment]
@ralfhandl 
> > servicePaths can be used to infer entity types that only exist for the purpose of defining path segments. There should be no need to define types for singletons when the only reason they exist is to create path segments for organizational purposes.

> Could someone please explain this statement?

Here's my thought process on this:
- servicePaths are completely optional for RSDL.  You could define a complete API using just navigation properties to define relationships and paths could be inferred as they are in CSDL
- servicePaths layer on top of the type model as way to express constraints. e.g. Which methods are supported. Which query parameters are supported.
- if you choose to use servicePaths, then entities that are created purely for the purpose of generating path segments, could be omitted from the type model.  Christof expressed an concern about this process and I think any discussion on introducing this shortcut can be deferred to some later time as it is not essential.

**Comment by garethj-msft** [comment]
> In addition to what Darrel said in the first bullet point, I like it just visually how the container type is separate from the paths and capabilities. I also don't mind the repetition of the prefixes (/e.g. /company/... ) It makes it very easy to read, explicit and is actually not difficult two write.
> I am not sure about the inference of entity types for singletons. I would probably prefer a very clear and easy to act on warning if the type is missing. Along the lines of "the segment 'bla' is not defined, it appears you are missing an entity type for the singleton 'bla' "

I'm in support of this approach.   A key behavior we want to support here is users who start their design with the paths and the HTTP methods, rather than with the entities and relationships.   That's quite often how folks designing with OpenAPI start out and we want to be able to naturally bring folks with that expertise into our ecosystem.  So keeping the paths as a separate top-level thing really seems to support that style of working.

It would be good in the medium term if tooling could infer a lot of different things.   For example, I might describe a set of path/method tuples that I intend my API to support, and then fill in a set of entities with no nav props that they operate over and have tooling infer the nav props from the paths rather than simply complain that they don't match.

**Comment by garethj-msft** [comment]
> > Without individualized names for identifiers, we won't later be able to add constraints to the model for what those identifiers should be where there is more than one in a path. This seems like it would be a real miss, when we want to specify that orderId is a Guid, plus a few magic values, but lineItemId is just a long.
> 
> Those restrictions are defined on the key properties in the resource type.
> 
> > There's really not a strong correspondence here in APIs between the Key of the type and what the values that can be passed as IDs in the path
> 
> In OData there is a strong correspondence: key segment values MUST match the type of the corresponding key property.
I think the type is fine, because in most cases on Graph, we just specify that keys must be singular, string and called 'id'.  
But it does limit entity type reuse if we define the values of this string at the type level instead of the path level.  Maybe we can live with that.

The practical paths we need to support are things like:

/mailboxes/<guid>
/mailboxes/<email@Address>
/mailboxes/<magicString>

So these are all strings, but they refer to different properties where the notion of associating<key> to a single OData property isn't what the API supports in practice (even though that is what we put in our CSDL for now). The alternate key syntax *might* also be supported but, in practice, no-one much on Graph uses it.

It's key to our needs for this new language that we find reasonably elegant ways to deal with these areas where Microsoft Graph stretches past the boundaries of the spec, as we will often place usability over standards adherence given interop is not our top priority.  So long as we can annotate for cases like this in some way that feels non-cumbersome, we'll be OK.

**Comment by ralfhandl** [comment]
> A key behavior we want to support here is users who start their design with the paths and the HTTP methods, rather than with the entities and relationships. That's quite often how folks designing with OpenAPI start out and we want to be able to naturally bring folks with that expertise into our ecosystem.

@garethj-msft I can understand that desire, but I'm not optimistic about the chances for success. 

Take the classic example for Swagger: https://petstore.swagger.io/:

![image](https://user-images.githubusercontent.com/951576/122100468-853d0000-ce13-11eb-8c8a-193c83ba19cf.png)

Which entities and relationships would we derive from these paths? 

This is by no means an untypical example, I've seen a lot of APIs that have very creative URL schemas, and freely mix more than one "pattern" in the same API. And I'm talking about the better-designed APIs, not about anti-patterns like

* `GET /importantStuff/{id}/delete` - deletes important stuff

**Comment by garethj-msft** [comment]
> > A key behavior we want to support here is users who start their design with the paths and the HTTP methods, rather than with the entities and relationships. That's quite often how folks designing with OpenAPI start out and we want to be able to naturally bring folks with that expertise into our ecosystem.
> 
> @garethj-msft I can understand that desire, but I'm not optimistic about the chances for success.
> 
> Take the classic example for Swagger: https://petstore.swagger.io/:
> 
> ![image](https://user-images.githubusercontent.com/951576/122100468-853d0000-ce13-11eb-8c8a-193c83ba19cf.png)
> 
> Which entities and relationships would we derive from these paths?
> 
> This is by no means an untypical example, I've seen a lot of APIs that have very creative URL schemas, and freely mix more than one "pattern" in the same API. And I'm talking about the better-designed APIs, not about anti-patterns like
> 
> * `GET /importantStuff/{id}/delete` - deletes important stuff

Fully agree with the general case @ralfhandl , but the case that concerns me is folks designing APIs that meet the Microsoft API design guidelines where we have guidance that path structures must follow OData's segment-based URL pattern.  I think we can generalize that such a language facility should work well for people who are choosing to start from paths but wish to make OData-shaped paths rather than arbitrary paths, given that if they started from data models they could only have the same set of paths.

I think this is a way of bringing in the spirit of how the wider community designs APIs without throwing out the OData bathwater.

**Comment by darrelmiller** [comment]
Curiously, the more recent versions of PetStore do actually use a plural path segment to indicate a collection.  https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml

**Comment by ralfhandl** [comment]
Looking at the [expanded petstore](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore-expanded.yaml), this begs to be an OData service - even the error response fits:

![Screenshot 2021-06-17 151923](https://user-images.githubusercontent.com/951576/122405087-0b765500-cf80-11eb-9bac-039a8e87542f.png)

**Comment by mikepizzo** [comment]
From brief discussion in 2021/6/17 meeting:
-No strong preference between putting paths side-by-side with the type defining the entityContainer or nested within the type defining the entityContainer
-We still want to have the keyword "service" for defining the (constrained) type defining the service.
-We prefer the keyword "path" to "servicePath"
-The syntax should require that the types be defined to support the paths, however tooling can highlight segments of the path that are not defined and offer "autoFix" functionality to auto-generate missing properties as appropriate
-For keys, Mike prefers putting the name of the property in the path, rather than a symbolic "key".  For multi-part keys, the path would contain a segment for each part of the multi-part key (which Mike also prefers). 
-Open issue as to how to handle scenarios where the service interprets the key segment as one of several different properties based on parsing the value.

**Comment by mikepizzo** [comment]
Proposed resolution in #249.
