### ISSUE TITLE
Normative grammar for RSDL 

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#251]
- Create a normative grammar for RSDL 
- In a central place 
- Grammar should be implementation independent and therefore in ABNF.

**Comment by chrisspre** [comment]
TODO: find a way to test ABNF against sample files without depending on specific parser implementation.

**Comment by ralfhandl** [comment]
For the OData ABNF we use [APG Java](https://github.com/ldthomas/apg-java) to generate a parser and run it via the [ABNF Test Tool](https://github.com/sap/abnf-test-tool)

**Comment by ralfhandl** [comment]
A better alternative is the [JavaScript implementation of APG](https://github.com/ldthomas/apg-js). It’s examples contain a JavaScript port of the [OData ABNF Test Tool](https://github.com/ldthomas/apg-js-examples/tree/main/src/odata)

**Comment by ralfhandl** [comment]
@chrisspre please check https://github.com/oasis-open/odata-rapid/tree/master/tools/rsdl/abnf (should have become a pull request - accidentally worked on master

**Comment by ralfhandl** [comment]
Our RSDL ABNF currently neither requires nor allows whitespace, and ABNF does not define/allow implicit whitespace - if we want to make it a full grammar, we have to explicitly specify whitespace.

Current status: 
- the first line correctly defines `service x` - no whitespace required after the `service` keyword
- the second line does not parse - now whitespace allowed
~~~
OK: servicex{foo:bar}      
KO: service x { foo : bar }
           ^
~~~
