### ISSUE TITLE
Documentation Revisions Proposal

### ISSUE THREAD

**Issue by lisicase** [oasis-open/odata-rapid#266]
# Specific Notes
#### Resource Description
- [x] "shape of your service" -> "shape of your API (the allowed requests, format of responses, and so forth.)"
##### Retrieving a Resource
- [x] Use a different term for $metadata than "resource" for clarity's sake -> "endpoint" / "...singleton defined in the $metadata document. The '@context' property is the URL representation of this section in the document, and in this example, it is a relative URL."
##### Modifying a Resource
- [x] Add summarizing sentence of code. E.g., "This example PATCH call replaces the name in the Company singleton."
#### Requesting a Range of Members
- [x] Explain the meaning of top/skip in a sentence-long parenthetical
#### Actions
- [x] Make it clear that the "side effects" are the intended changes to the data
### Runtime Service Description
- [x] Categorize into sections to make the content easier to digest. E.g., Types, Properties {Meta, Dynamic}, Entities
##### Defining a Structured Type Property
- [x] Add a PATCH example (e.g., Request: PATCH http://rapid-pro.org/company/employees/1
{ "title": "senior manager" }; Comment: change the title of the employee with id=1)
##### Defining a Structured Property without Identity
- [x] Explain motivation. E.g., "Grouping these properties together makes them easy to use in various entities."
##### Structured Types without `key` Properties
- [x] Explain motivation. E.g., "Complex types do not use an ID, as they are intended for organizing related properties into a group that is non-unique and does not stand alone."
- [x] Add more introductions to each section being an example of a structured type that gets mapped from RSDL to CSDL (used by OData)
# General Notes
- [x] Be intentional about the use of "service" vs. "API" ("API" for description, "service" for when it runs, everything else is a judgment call)
- [ ] Make keywords clear that they are keywords (e.g., "type", "service")
- [x] Make the order of "Features" and "Actions" consistent throughout

**Comment by mikepizzo** [comment]
Addressed by oasis-open#266
