### ISSUE TITLE
Building dependencies for website deployment of urlEditor

### ISSUE THREAD

**Issue by lisicase** [oasis-open/odata-rapid#284]
PR#276 (which includes PR#272) builds locally with the following commands:

- in odataUri: `npm run build`
- in urlEditor: `npm run build`
- in website: `npm run start`

However, despite adding this process to the overall website build script in website.yml, it does not build urlEditor correctly. This issue is for addressing that problem so that PR#276 can be merged.

For reference, there are three possible overarching approaches to building the proper dependencies, the third approach having been previously chosen for the short term:

1. Set up the project as a monorepo or use the yarn workspaces feature so that building the website will automatically build its local package dependencies.
2. Publish the urlEditr and odata-uri to npm. That way, running npm install will install them directly from npm, and when we publish to npm, we publish their build assets.
3. Add a command as part of the site's build steps that manually goes to the appropriate directories and runs `npm run build`.

**Comment by chrisspre** [comment]
In addition to what Lisi said, I would suggest to do some more housekeeping
- the readme states to use yarn build and yarn publish. usage or yarn vs npm should be consistent. 
- the two components should be moved under the website folder to make the site a bit more self contained
- the naming of the folders/modules/package of the two component should be more consistent
- the one component builds its dependency (yarn build in the tools/urlEditor build it and odataUri), can the same mechanism be used for yarn build in the website.

**Comment by ralfhandl** [comment]
Issue seems fixed now
