### ISSUE TITLE
disable swagger's "try-it-now" 

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#373]
Since there is not service YET in the API designer , the "try-it-now" button just creates an error.
For the moment this should be disabled and only enabled when we can generate and host a service based on the designed RSDL.

**Comment by chrisspre** [comment]
found the following [c.SupportedSubmitMethods (new string [] {}); will completely disable “Try it out”](https://stackoverflow.com/questions/43149883/servicestack-swagger-api-supportedsubmitmethods)

**Comment by chrisspre** [comment]
see https://github.com/oasis-open/odata-rapid/tree/disable-swagger-try-button
which is untested as of now due to build issues

**Comment by mikepizzo** [comment]
Fixed by PR #374.
