### ISSUE TITLE
Create logo for RAPID

### ISSUE THREAD

**Issue by wtrocki** [oasis-open/odata-rapid#73]
Simple logo `R[API]D` would be good starting point
Something like:

<img width="382" alt="Screenshot 2020-06-18 at 22 58 25" src="https://user-images.githubusercontent.com/981838/85075965-41d79380-b1b7-11ea-90ec-e706a96c37bf.png">

**Comment by GEricson** [comment]
A fun alternative.
![RAPID (2)](https://user-images.githubusercontent.com/12564695/90799607-74019080-e2e1-11ea-8732-4cd5a5bbc846.jpg)

**Comment by chrisspre** [comment]
![rapid-02](https://user-images.githubusercontent.com/53094940/97904609-99eddd00-1cf5-11eb-9a8e-d894c66d6dcb.png)

**Comment by GEricson** [comment]
I like the rabbit.  Here are two more that use the rabbit.
![image](https://user-images.githubusercontent.com/12564695/100147428-5f491180-2e69-11eb-8352-707fcefc2f86.png)
![image](https://user-images.githubusercontent.com/12564695/100147726-be0e8b00-2e69-11eb-8b80-5d831af9d9b1.png)

**Comment by GEricson** [comment]
And some new with the old.
![image](https://user-images.githubusercontent.com/12564695/100875789-7ba20b00-3474-11eb-927c-6eb2a9f15c2f.png)

**Comment by GEricson** [comment]
![image](https://user-images.githubusercontent.com/12564695/101022546-8675a200-353f-11eb-9e01-5ee53377fe0c.png)

**Comment by ralfhandl** [comment]
Don't hide the rabbit behind the OData logo, put him above _RAPID_

**Comment by chrisspre** [comment]
![image](https://user-images.githubusercontent.com/53094940/101818086-3915a980-3ad8-11eb-8908-f0d279cf82a9.png)

**Comment by mikepizzo** [comment]
Bunny facing right over RAPID:
![image](https://user-images.githubusercontent.com/8660830/109186613-f57d2400-7745-11eb-8de0-77c13a69abcb.png)

**Comment by mikepizzo** [comment]
Voted 2021/2/25 to use above logo.

**Comment by chrisspre** [comment]
It might be important to be a bit more specific about that logo. It is very easy to copy, move distort such a logo and end up with something that looks quite different.
my suggestions/questions :
- colors are black #000000 for letters R and D, orange #C55A11 for the letters A,P,I
- rabbit outline is black and filled white
- rabbit is facing right
- rabbit is composed of four contiguous parts (left ear, tail, front paw, remainder (body, head, ...) ) the pieces do not touch and have a visible gap in-between
- both the text and rabbit outline fit in a rectangular outline box .
  - the width of the rabbit is equal to the width of the text
  - the ratio between height and width is roughly  3.3 : 3.0
